### ISSUE TITLE
wrong call to $ipn->failed function

### ISSUE THREAD

**Issue by catorghans** [eileenmcnaughton/nz.co.fuzion.cmcic#1]
In function "processFailedTransaction" there is a call to
$ipn->failed($input, $ids, $objects, $transaction);

It seems to do nothing.

If I look at that function (civicrm 4.4.5) it should be
$ipn->failed($objects, $transaction, $input);
And then I get a proper update of that Contribution.

Hans Idink

**Comment by eileenmcnaughton** [comment]
Thanks for that - do you want to check the commit https://github.com/eileenmcnaughton/nz.co.fuzion.cmcic/commit/b2c8eb51a9c0f09d3d9c3cbe4d878b362dff339c

**Comment by catorghans** [comment]
Well, I don't have a CMCIC account, I used your code for my new payment provider, there it works

https://github.com/catorghans/org.civicoop.orgis.omnikassa/blob/master/CRM/Core/Payment/OmnikassaIPN.php
