### ISSUE TITLE
Return URL IPN issue

### ISSUE THREAD

**Issue by stiix13** [eileenmcnaughton/nz.co.fuzion.cmcic#5]
On Joomla 3.8.2, PHP 5.6.31, CiviCRM 4.7.27
The return URL https://[SITENAME]/civicrm/payment/ipn?processor_id=1 as specified in the info.xml isn't working for me, I have a "Not found" error.
I've tried
https://[SITENAME]/administrator/components/com_civicrm/civicrm/payment/ipn?processor_id=1 - Give the same result (404)
https://[SITENAME]/administrator/components/com_civicrm/civicrm/extern/ipn.php?processor_id=1 - Give me a blank page

I would go for the second URL, but how could I check if I have the right IPN return URL before sending it to the bank?

**Comment by eileenmcnaughton** [comment]
try https://[SITENAME]/administrator/components/com_civicrm/civicrm/payment/ipn/1

-although I wonder if it should be 

https://[SITENAME]/components/com_civicrm/civicrm/payment/ipn/1

**Comment by stiix13** [comment]
Thanks for your fast reply. Should I have the "No direct access allowed" message if I go to the page from my browser?
What worked for me was https://[SITENAME]/components/com_civicrm/civicrm/payment/ipn/1  on Joomla

**Comment by eileenmcnaughton** [comment]
I think you should be able to get there in your browser - but get a failure message about missing parameter or somethin

**Comment by stiix13** [comment]
So after a few test I've been able to find the return URL, I'll put it here for the next one.
My contribution page was at this adress:
https://example.org/index.php?option=com_civicrm&task=civicrm/contribute/transact&reset=1&id=2
(ID 2 because I have two pages)
My return URL was
https://example.org/index.php?option=com_civicrm&task=civicrm/payment/ipn&processor_id=1
(processor_id 1 because it's the first plugins for payement I have, you can find out in the "gateway paiement" page when you edit your gateway, in the URL)
If you go directly on the return URL, you should have a blank page with "version=2 cdr=1" written.

Thanks for your work

**Comment by eileenmcnaughton** [comment]
@stiix13 any chance you could do a PR against the readme to give the info that would have helped you?

**Comment by stiix13** [comment]
@eileenmcnaughton  Could you allow me to commit branch, or create me a new one? I can't do PR on master, and can't push new branch

**Comment by eileenmcnaughton** [comment]
@stiix13 you should be able to fork the repo & push to your version - then you can create a PR

**Comment by stiix13** [comment]
Thanks, PR opened, I'm closing this issue
